//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassyAds_Web_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_des { get; set; }
        public Nullable<int> pro_view { get; set; }
        public string pro_address { get; set; }
        public string pro_image1 { get; set; }
        public string pro_image2 { get; set; }
        public string pro_image3 { get; set; }
        public Nullable<int> pro_fk_user { get; set; }
        public Nullable<int> pro_fk_cat { get; set; }
        public string pro_contact { get; set; }
        public string pro_price { get; set; }
        public Nullable<bool> Featured { get; set; }
        public Nullable<bool> Popular_Products { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
