//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassyAds_Web_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product_no
    {
        public int n_id { get; set; }
        public Nullable<int> n_no { get; set; }
        public Nullable<int> n_fk_cat { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
    }
}
